/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SharedExpenseGroup {
    id: bigint;
    creator: Principal;
    members: Array<Principal>;
    name: string;
}
export interface SharedExpense {
    id: bigint;
    settlements: Array<[Principal, boolean]>;
    splitType: Variant_custom_equal;
    description: string;
    groupId: bigint;
    totalAmount: number;
    customSplits: Array<[Principal, number]>;
    paidBy: Principal;
}
export interface Expense {
    id: bigint;
    date: string;
    note?: string;
    category: string;
    amount: number;
}
export interface UserProfile {
    age: bigint;
    findsAppsUseful: boolean;
    previousAppName?: string;
    tracksDailyExpenses: boolean;
    livingSituation: LivingSituation;
    biggestFinancialProblem: string;
    name: string;
    featurePreferences: Array<string>;
    conflictFrequency: ConflictFrequency;
    incomeSource: IncomeSource;
    borrowsDueToBudget: boolean;
    majorSpendingCategory: string;
    gender: Gender;
    financialStressLevel: bigint;
    hasSharedExpenses: boolean;
    course: string;
    prefersAutoSplit: boolean;
    hasEmergencySavings: boolean;
    setsMonthlyBudget: boolean;
    monthEndShortage: boolean;
    monthlyIncome: number;
    budgetDisciplineLevel: BudgetDisciplineLevel;
}
export enum BudgetDisciplineLevel {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum ConflictFrequency {
    often = "often",
    never_ = "never",
    sometimes = "sometimes",
    rarely = "rarely"
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male"
}
export enum IncomeSource {
    scholarship = "scholarship",
    other = "other",
    partTimeJob = "partTimeJob",
    allowance = "allowance"
}
export enum LivingSituation {
    withParents = "withParents",
    onCampus = "onCampus",
    offCampus = "offCampus"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_custom_equal {
    custom = "custom",
    equal = "equal"
}
export enum Variant_warning_exceeded_critical {
    warning = "warning",
    exceeded = "exceeded",
    critical = "critical"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCustomCategory(name: string): Promise<void>;
    addExpense(amount: number, category: string, date: string, note: string | null): Promise<bigint>;
    addGroupMember(groupId: bigint, member: Principal): Promise<void>;
    addSharedExpense(groupId: bigint, description: string, totalAmount: number, paidBy: Principal, splitType: Variant_custom_equal, customSplits: Array<[Principal, number]>): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createGroup(name: string): Promise<bigint>;
    deleteCustomCategory(name: string): Promise<void>;
    deleteExpense(id: bigint): Promise<void>;
    deleteGroup(groupId: bigint): Promise<void>;
    editExpense(id: bigint, amount: number, category: string, date: string, note: string | null): Promise<void>;
    getAlerts(month: string): Promise<Array<{
        alertType: Variant_warning_exceeded_critical;
        message: string;
        category: string;
    }>>;
    getBudgetSummary(month: string): Promise<{
        categories: Array<{
            limit: number;
            totalSpent: number;
            percentageUsed: number;
            category: string;
            remaining: number;
        }>;
        totalIncome: number;
        incomeToExpenseRatio: number;
        totalExpenses: number;
    }>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFinancialScore(): Promise<{
        savingTips: Array<string>;
        highestSpendingCategory: string;
        emergencyFundRecommendation: number;
        disciplineLevel: string;
        weeklySpendingCap: number;
        borrowingRisk: string;
        monthlyTrend: Array<{
            month: string;
            total: number;
        }>;
        financialScore: number;
    }>;
    getSettlementSummary(groupId: bigint): Promise<Array<[Principal, Principal, number]>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listCategories(): Promise<Array<string>>;
    listExpenses(categoryFilter: string | null, monthFilter: string | null): Promise<Array<Expense>>;
    listGroups(): Promise<Array<SharedExpenseGroup>>;
    listSharedExpenses(groupId: bigint): Promise<Array<SharedExpense>>;
    markSplitPaid(groupId: bigint, expenseId: bigint): Promise<void>;
    removeGroupMember(groupId: bigint, member: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setMonthlyBudget(category: string, amount: number): Promise<void>;
}
import type { BudgetDisciplineLevel as _BudgetDisciplineLevel, ConflictFrequency as _ConflictFrequency, Expense as _Expense, Gender as _Gender, IncomeSource as _IncomeSource, LivingSituation as _LivingSituation, SharedExpense as _SharedExpense, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCustomCategory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomCategory(arg0);
            return result;
        }
    }
    async addExpense(arg0: number, arg1: string, arg2: string, arg3: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpense(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpense(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async addGroupMember(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGroupMember(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGroupMember(arg0, arg1);
            return result;
        }
    }
    async addSharedExpense(arg0: bigint, arg1: string, arg2: number, arg3: Principal, arg4: Variant_custom_equal, arg5: Array<[Principal, number]>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSharedExpense(arg0, arg1, arg2, arg3, to_candid_variant_n2(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSharedExpense(arg0, arg1, arg2, arg3, to_candid_variant_n2(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createGroup(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGroup(arg0);
            return result;
        }
    }
    async deleteCustomCategory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomCategory(arg0);
            return result;
        }
    }
    async deleteExpense(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpense(arg0);
            return result;
        }
    }
    async deleteGroup(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGroup(arg0);
            return result;
        }
    }
    async editExpense(arg0: bigint, arg1: number, arg2: string, arg3: string, arg4: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editExpense(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editExpense(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async getAlerts(arg0: string): Promise<Array<{
        alertType: Variant_warning_exceeded_critical;
        message: string;
        category: string;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlerts(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlerts(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBudgetSummary(arg0: string): Promise<{
        categories: Array<{
            limit: number;
            totalSpent: number;
            percentageUsed: number;
            category: string;
            remaining: number;
        }>;
        totalIncome: number;
        incomeToExpenseRatio: number;
        totalExpenses: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getBudgetSummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBudgetSummary(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFinancialScore(): Promise<{
        savingTips: Array<string>;
        highestSpendingCategory: string;
        emergencyFundRecommendation: number;
        disciplineLevel: string;
        weeklySpendingCap: number;
        borrowingRisk: string;
        monthlyTrend: Array<{
            month: string;
            total: number;
        }>;
        financialScore: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getFinancialScore();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFinancialScore();
            return result;
        }
    }
    async getSettlementSummary(arg0: bigint): Promise<Array<[Principal, Principal, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettlementSummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettlementSummary(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listCategories(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCategories();
            return result;
        }
    }
    async listExpenses(arg0: string | null, arg1: string | null): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.listExpenses(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listExpenses(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async listGroups(): Promise<Array<SharedExpenseGroup>> {
        if (this.processError) {
            try {
                const result = await this.actor.listGroups();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listGroups();
            return result;
        }
    }
    async listSharedExpenses(arg0: bigint): Promise<Array<SharedExpense>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSharedExpenses(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSharedExpenses(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async markSplitPaid(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markSplitPaid(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markSplitPaid(arg0, arg1);
            return result;
        }
    }
    async removeGroupMember(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeGroupMember(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeGroupMember(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n31(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n31(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setMonthlyBudget(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMonthlyBudget(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMonthlyBudget(arg0, arg1);
            return result;
        }
    }
}
function from_candid_BudgetDisciplineLevel_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BudgetDisciplineLevel): BudgetDisciplineLevel {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_ConflictFrequency_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConflictFrequency): ConflictFrequency {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Expense_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Expense): Expense {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Gender_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_IncomeSource_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IncomeSource): IncomeSource {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_LivingSituation_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LivingSituation): LivingSituation {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_SharedExpense_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SharedExpense): SharedExpense {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    findsAppsUseful: boolean;
    previousAppName: [] | [string];
    tracksDailyExpenses: boolean;
    livingSituation: _LivingSituation;
    biggestFinancialProblem: string;
    name: string;
    featurePreferences: Array<string>;
    conflictFrequency: _ConflictFrequency;
    incomeSource: _IncomeSource;
    borrowsDueToBudget: boolean;
    majorSpendingCategory: string;
    gender: _Gender;
    financialStressLevel: bigint;
    hasSharedExpenses: boolean;
    course: string;
    prefersAutoSplit: boolean;
    hasEmergencySavings: boolean;
    setsMonthlyBudget: boolean;
    monthEndShortage: boolean;
    monthlyIncome: number;
    budgetDisciplineLevel: _BudgetDisciplineLevel;
}): {
    age: bigint;
    findsAppsUseful: boolean;
    previousAppName?: string;
    tracksDailyExpenses: boolean;
    livingSituation: LivingSituation;
    biggestFinancialProblem: string;
    name: string;
    featurePreferences: Array<string>;
    conflictFrequency: ConflictFrequency;
    incomeSource: IncomeSource;
    borrowsDueToBudget: boolean;
    majorSpendingCategory: string;
    gender: Gender;
    financialStressLevel: bigint;
    hasSharedExpenses: boolean;
    course: string;
    prefersAutoSplit: boolean;
    hasEmergencySavings: boolean;
    setsMonthlyBudget: boolean;
    monthEndShortage: boolean;
    monthlyIncome: number;
    budgetDisciplineLevel: BudgetDisciplineLevel;
} {
    return {
        age: value.age,
        findsAppsUseful: value.findsAppsUseful,
        previousAppName: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.previousAppName)),
        tracksDailyExpenses: value.tracksDailyExpenses,
        livingSituation: from_candid_LivingSituation_n12(_uploadFile, _downloadFile, value.livingSituation),
        biggestFinancialProblem: value.biggestFinancialProblem,
        name: value.name,
        featurePreferences: value.featurePreferences,
        conflictFrequency: from_candid_ConflictFrequency_n14(_uploadFile, _downloadFile, value.conflictFrequency),
        incomeSource: from_candid_IncomeSource_n16(_uploadFile, _downloadFile, value.incomeSource),
        borrowsDueToBudget: value.borrowsDueToBudget,
        majorSpendingCategory: value.majorSpendingCategory,
        gender: from_candid_Gender_n18(_uploadFile, _downloadFile, value.gender),
        financialStressLevel: value.financialStressLevel,
        hasSharedExpenses: value.hasSharedExpenses,
        course: value.course,
        prefersAutoSplit: value.prefersAutoSplit,
        hasEmergencySavings: value.hasEmergencySavings,
        setsMonthlyBudget: value.setsMonthlyBudget,
        monthEndShortage: value.monthEndShortage,
        monthlyIncome: value.monthlyIncome,
        budgetDisciplineLevel: from_candid_BudgetDisciplineLevel_n20(_uploadFile, _downloadFile, value.budgetDisciplineLevel)
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    date: string;
    note: [] | [string];
    category: string;
    amount: number;
}): {
    id: bigint;
    date: string;
    note?: string;
    category: string;
    amount: number;
} {
    return {
        id: value.id,
        date: value.date,
        note: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.note)),
        category: value.category,
        amount: value.amount
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    settlements: Array<[Principal, boolean]>;
    splitType: {
        custom: null;
    } | {
        equal: null;
    };
    description: string;
    groupId: bigint;
    totalAmount: number;
    customSplits: Array<[Principal, number]>;
    paidBy: Principal;
}): {
    id: bigint;
    settlements: Array<[Principal, boolean]>;
    splitType: Variant_custom_equal;
    description: string;
    groupId: bigint;
    totalAmount: number;
    customSplits: Array<[Principal, number]>;
    paidBy: Principal;
} {
    return {
        id: value.id,
        settlements: value.settlements,
        splitType: from_candid_variant_n30(_uploadFile, _downloadFile, value.splitType),
        description: value.description,
        groupId: value.groupId,
        totalAmount: value.totalAmount,
        customSplits: value.customSplits,
        paidBy: value.paidBy
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    alertType: {
        warning: null;
    } | {
        exceeded: null;
    } | {
        critical: null;
    };
    message: string;
    category: string;
}): {
    alertType: Variant_warning_exceeded_critical;
    message: string;
    category: string;
} {
    return {
        alertType: from_candid_variant_n7(_uploadFile, _downloadFile, value.alertType),
        message: value.message,
        category: value.category
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    withParents: null;
} | {
    onCampus: null;
} | {
    offCampus: null;
}): LivingSituation {
    return "withParents" in value ? LivingSituation.withParents : "onCampus" in value ? LivingSituation.onCampus : "offCampus" in value ? LivingSituation.offCampus : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    often: null;
} | {
    never: null;
} | {
    sometimes: null;
} | {
    rarely: null;
}): ConflictFrequency {
    return "often" in value ? ConflictFrequency.often : "never" in value ? ConflictFrequency.never : "sometimes" in value ? ConflictFrequency.sometimes : "rarely" in value ? ConflictFrequency.rarely : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scholarship: null;
} | {
    other: null;
} | {
    partTimeJob: null;
} | {
    allowance: null;
}): IncomeSource {
    return "scholarship" in value ? IncomeSource.scholarship : "other" in value ? IncomeSource.other : "partTimeJob" in value ? IncomeSource.partTimeJob : "allowance" in value ? IncomeSource.allowance : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): BudgetDisciplineLevel {
    return "low" in value ? BudgetDisciplineLevel.low : "high" in value ? BudgetDisciplineLevel.high : "medium" in value ? BudgetDisciplineLevel.medium : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    custom: null;
} | {
    equal: null;
}): Variant_custom_equal {
    return "custom" in value ? Variant_custom_equal.custom : "equal" in value ? Variant_custom_equal.equal : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    warning: null;
} | {
    exceeded: null;
} | {
    critical: null;
}): Variant_warning_exceeded_critical {
    return "warning" in value ? Variant_warning_exceeded_critical.warning : "exceeded" in value ? Variant_warning_exceeded_critical.exceeded : "critical" in value ? Variant_warning_exceeded_critical.critical : value;
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Expense>): Array<Expense> {
    return value.map((x)=>from_candid_Expense_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SharedExpense>): Array<SharedExpense> {
    return value.map((x)=>from_candid_SharedExpense_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<{
    alertType: {
        warning: null;
    } | {
        exceeded: null;
    } | {
        critical: null;
    };
    message: string;
    category: string;
}>): Array<{
    alertType: Variant_warning_exceeded_critical;
    message: string;
    category: string;
}> {
    return value.map((x)=>from_candid_record_n6(_uploadFile, _downloadFile, x));
}
function to_candid_BudgetDisciplineLevel_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BudgetDisciplineLevel): _BudgetDisciplineLevel {
    return to_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function to_candid_ConflictFrequency_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConflictFrequency): _ConflictFrequency {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_Gender_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function to_candid_IncomeSource_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IncomeSource): _IncomeSource {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function to_candid_LivingSituation_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LivingSituation): _LivingSituation {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    findsAppsUseful: boolean;
    previousAppName?: string;
    tracksDailyExpenses: boolean;
    livingSituation: LivingSituation;
    biggestFinancialProblem: string;
    name: string;
    featurePreferences: Array<string>;
    conflictFrequency: ConflictFrequency;
    incomeSource: IncomeSource;
    borrowsDueToBudget: boolean;
    majorSpendingCategory: string;
    gender: Gender;
    financialStressLevel: bigint;
    hasSharedExpenses: boolean;
    course: string;
    prefersAutoSplit: boolean;
    hasEmergencySavings: boolean;
    setsMonthlyBudget: boolean;
    monthEndShortage: boolean;
    monthlyIncome: number;
    budgetDisciplineLevel: BudgetDisciplineLevel;
}): {
    age: bigint;
    findsAppsUseful: boolean;
    previousAppName: [] | [string];
    tracksDailyExpenses: boolean;
    livingSituation: _LivingSituation;
    biggestFinancialProblem: string;
    name: string;
    featurePreferences: Array<string>;
    conflictFrequency: _ConflictFrequency;
    incomeSource: _IncomeSource;
    borrowsDueToBudget: boolean;
    majorSpendingCategory: string;
    gender: _Gender;
    financialStressLevel: bigint;
    hasSharedExpenses: boolean;
    course: string;
    prefersAutoSplit: boolean;
    hasEmergencySavings: boolean;
    setsMonthlyBudget: boolean;
    monthEndShortage: boolean;
    monthlyIncome: number;
    budgetDisciplineLevel: _BudgetDisciplineLevel;
} {
    return {
        age: value.age,
        findsAppsUseful: value.findsAppsUseful,
        previousAppName: value.previousAppName ? candid_some(value.previousAppName) : candid_none(),
        tracksDailyExpenses: value.tracksDailyExpenses,
        livingSituation: to_candid_LivingSituation_n33(_uploadFile, _downloadFile, value.livingSituation),
        biggestFinancialProblem: value.biggestFinancialProblem,
        name: value.name,
        featurePreferences: value.featurePreferences,
        conflictFrequency: to_candid_ConflictFrequency_n35(_uploadFile, _downloadFile, value.conflictFrequency),
        incomeSource: to_candid_IncomeSource_n37(_uploadFile, _downloadFile, value.incomeSource),
        borrowsDueToBudget: value.borrowsDueToBudget,
        majorSpendingCategory: value.majorSpendingCategory,
        gender: to_candid_Gender_n39(_uploadFile, _downloadFile, value.gender),
        financialStressLevel: value.financialStressLevel,
        hasSharedExpenses: value.hasSharedExpenses,
        course: value.course,
        prefersAutoSplit: value.prefersAutoSplit,
        hasEmergencySavings: value.hasEmergencySavings,
        setsMonthlyBudget: value.setsMonthlyBudget,
        monthEndShortage: value.monthEndShortage,
        monthlyIncome: value.monthlyIncome,
        budgetDisciplineLevel: to_candid_BudgetDisciplineLevel_n41(_uploadFile, _downloadFile, value.budgetDisciplineLevel)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_custom_equal): {
    custom: null;
} | {
    equal: null;
} {
    return value == Variant_custom_equal.custom ? {
        custom: null
    } : value == Variant_custom_equal.equal ? {
        equal: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LivingSituation): {
    withParents: null;
} | {
    onCampus: null;
} | {
    offCampus: null;
} {
    return value == LivingSituation.withParents ? {
        withParents: null
    } : value == LivingSituation.onCampus ? {
        onCampus: null
    } : value == LivingSituation.offCampus ? {
        offCampus: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConflictFrequency): {
    often: null;
} | {
    never: null;
} | {
    sometimes: null;
} | {
    rarely: null;
} {
    return value == ConflictFrequency.often ? {
        often: null
    } : value == ConflictFrequency.never ? {
        never_: null
    } : value == ConflictFrequency.sometimes ? {
        sometimes: null
    } : value == ConflictFrequency.rarely ? {
        rarely: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IncomeSource): {
    scholarship: null;
} | {
    other: null;
} | {
    partTimeJob: null;
} | {
    allowance: null;
} {
    return value == IncomeSource.scholarship ? {
        scholarship: null
    } : value == IncomeSource.other ? {
        other: null
    } : value == IncomeSource.partTimeJob ? {
        partTimeJob: null
    } : value == IncomeSource.allowance ? {
        allowance: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
function to_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BudgetDisciplineLevel): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == BudgetDisciplineLevel.low ? {
        low: null
    } : value == BudgetDisciplineLevel.high ? {
        high: null
    } : value == BudgetDisciplineLevel.medium ? {
        medium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
