/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BudgetDisciplineLevel = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type ConflictFrequency = { 'often' : null } |
  { 'never' : null } |
  { 'sometimes' : null } |
  { 'rarely' : null };
export interface Expense {
  'id' : bigint,
  'date' : string,
  'note' : [] | [string],
  'category' : string,
  'amount' : number,
}
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export type IncomeSource = { 'scholarship' : null } |
  { 'other' : null } |
  { 'partTimeJob' : null } |
  { 'allowance' : null };
export type LivingSituation = { 'withParents' : null } |
  { 'onCampus' : null } |
  { 'offCampus' : null };
export interface SharedExpense {
  'id' : bigint,
  'settlements' : Array<[Principal, boolean]>,
  'splitType' : { 'custom' : null } |
    { 'equal' : null },
  'description' : string,
  'groupId' : bigint,
  'totalAmount' : number,
  'customSplits' : Array<[Principal, number]>,
  'paidBy' : Principal,
}
export interface SharedExpenseGroup {
  'id' : bigint,
  'creator' : Principal,
  'members' : Array<Principal>,
  'name' : string,
}
export interface UserProfile {
  'age' : bigint,
  'findsAppsUseful' : boolean,
  'previousAppName' : [] | [string],
  'tracksDailyExpenses' : boolean,
  'livingSituation' : LivingSituation,
  'biggestFinancialProblem' : string,
  'name' : string,
  'featurePreferences' : Array<string>,
  'conflictFrequency' : ConflictFrequency,
  'incomeSource' : IncomeSource,
  'borrowsDueToBudget' : boolean,
  'majorSpendingCategory' : string,
  'gender' : Gender,
  'financialStressLevel' : bigint,
  'hasSharedExpenses' : boolean,
  'course' : string,
  'prefersAutoSplit' : boolean,
  'hasEmergencySavings' : boolean,
  'setsMonthlyBudget' : boolean,
  'monthEndShortage' : boolean,
  'monthlyIncome' : number,
  'budgetDisciplineLevel' : BudgetDisciplineLevel,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCustomCategory' : ActorMethod<[string], undefined>,
  'addExpense' : ActorMethod<[number, string, string, [] | [string]], bigint>,
  'addGroupMember' : ActorMethod<[bigint, Principal], undefined>,
  'addSharedExpense' : ActorMethod<
    [
      bigint,
      string,
      number,
      Principal,
      { 'custom' : null } |
        { 'equal' : null },
      Array<[Principal, number]>,
    ],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createGroup' : ActorMethod<[string], bigint>,
  'deleteCustomCategory' : ActorMethod<[string], undefined>,
  'deleteExpense' : ActorMethod<[bigint], undefined>,
  'deleteGroup' : ActorMethod<[bigint], undefined>,
  'editExpense' : ActorMethod<
    [bigint, number, string, string, [] | [string]],
    undefined
  >,
  'getAlerts' : ActorMethod<
    [string],
    Array<
      {
        'alertType' : { 'warning' : null } |
          { 'exceeded' : null } |
          { 'critical' : null },
        'message' : string,
        'category' : string,
      }
    >
  >,
  'getBudgetSummary' : ActorMethod<
    [string],
    {
      'categories' : Array<
        {
          'limit' : number,
          'totalSpent' : number,
          'percentageUsed' : number,
          'category' : string,
          'remaining' : number,
        }
      >,
      'totalIncome' : number,
      'incomeToExpenseRatio' : number,
      'totalExpenses' : number,
    }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFinancialScore' : ActorMethod<
    [],
    {
      'savingTips' : Array<string>,
      'highestSpendingCategory' : string,
      'emergencyFundRecommendation' : number,
      'disciplineLevel' : string,
      'weeklySpendingCap' : number,
      'borrowingRisk' : string,
      'monthlyTrend' : Array<{ 'month' : string, 'total' : number }>,
      'financialScore' : number,
    }
  >,
  'getSettlementSummary' : ActorMethod<
    [bigint],
    Array<[Principal, Principal, number]>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCategories' : ActorMethod<[], Array<string>>,
  'listExpenses' : ActorMethod<[[] | [string], [] | [string]], Array<Expense>>,
  'listGroups' : ActorMethod<[], Array<SharedExpenseGroup>>,
  'listSharedExpenses' : ActorMethod<[bigint], Array<SharedExpense>>,
  'markSplitPaid' : ActorMethod<[bigint, bigint], undefined>,
  'removeGroupMember' : ActorMethod<[bigint, Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setMonthlyBudget' : ActorMethod<[string, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];