/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LivingSituation = IDL.Variant({
  'withParents' : IDL.Null,
  'onCampus' : IDL.Null,
  'offCampus' : IDL.Null,
});
export const ConflictFrequency = IDL.Variant({
  'often' : IDL.Null,
  'never' : IDL.Null,
  'sometimes' : IDL.Null,
  'rarely' : IDL.Null,
});
export const IncomeSource = IDL.Variant({
  'scholarship' : IDL.Null,
  'other' : IDL.Null,
  'partTimeJob' : IDL.Null,
  'allowance' : IDL.Null,
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const BudgetDisciplineLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'findsAppsUseful' : IDL.Bool,
  'previousAppName' : IDL.Opt(IDL.Text),
  'tracksDailyExpenses' : IDL.Bool,
  'livingSituation' : LivingSituation,
  'biggestFinancialProblem' : IDL.Text,
  'name' : IDL.Text,
  'featurePreferences' : IDL.Vec(IDL.Text),
  'conflictFrequency' : ConflictFrequency,
  'incomeSource' : IncomeSource,
  'borrowsDueToBudget' : IDL.Bool,
  'majorSpendingCategory' : IDL.Text,
  'gender' : Gender,
  'financialStressLevel' : IDL.Nat,
  'hasSharedExpenses' : IDL.Bool,
  'course' : IDL.Text,
  'prefersAutoSplit' : IDL.Bool,
  'hasEmergencySavings' : IDL.Bool,
  'setsMonthlyBudget' : IDL.Bool,
  'monthEndShortage' : IDL.Bool,
  'monthlyIncome' : IDL.Float64,
  'budgetDisciplineLevel' : BudgetDisciplineLevel,
});
export const Expense = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const SharedExpenseGroup = IDL.Record({
  'id' : IDL.Nat,
  'creator' : IDL.Principal,
  'members' : IDL.Vec(IDL.Principal),
  'name' : IDL.Text,
});
export const SharedExpense = IDL.Record({
  'id' : IDL.Nat,
  'settlements' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Bool)),
  'splitType' : IDL.Variant({ 'custom' : IDL.Null, 'equal' : IDL.Null }),
  'description' : IDL.Text,
  'groupId' : IDL.Nat,
  'totalAmount' : IDL.Float64,
  'customSplits' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Float64)),
  'paidBy' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCustomCategory' : IDL.Func([IDL.Text], [], []),
  'addExpense' : IDL.Func(
      [IDL.Float64, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'addGroupMember' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'addSharedExpense' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Float64,
        IDL.Principal,
        IDL.Variant({ 'custom' : IDL.Null, 'equal' : IDL.Null }),
        IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Float64)),
      ],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGroup' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'deleteCustomCategory' : IDL.Func([IDL.Text], [], []),
  'deleteExpense' : IDL.Func([IDL.Nat], [], []),
  'deleteGroup' : IDL.Func([IDL.Nat], [], []),
  'editExpense' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'getAlerts' : IDL.Func(
      [IDL.Text],
      [
        IDL.Vec(
          IDL.Record({
            'alertType' : IDL.Variant({
              'warning' : IDL.Null,
              'exceeded' : IDL.Null,
              'critical' : IDL.Null,
            }),
            'message' : IDL.Text,
            'category' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getBudgetSummary' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'categories' : IDL.Vec(
            IDL.Record({
              'limit' : IDL.Float64,
              'totalSpent' : IDL.Float64,
              'percentageUsed' : IDL.Float64,
              'category' : IDL.Text,
              'remaining' : IDL.Float64,
            })
          ),
          'totalIncome' : IDL.Float64,
          'incomeToExpenseRatio' : IDL.Float64,
          'totalExpenses' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFinancialScore' : IDL.Func(
      [],
      [
        IDL.Record({
          'savingTips' : IDL.Vec(IDL.Text),
          'highestSpendingCategory' : IDL.Text,
          'emergencyFundRecommendation' : IDL.Float64,
          'disciplineLevel' : IDL.Text,
          'weeklySpendingCap' : IDL.Float64,
          'borrowingRisk' : IDL.Text,
          'monthlyTrend' : IDL.Vec(
            IDL.Record({ 'month' : IDL.Text, 'total' : IDL.Float64 })
          ),
          'financialScore' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getSettlementSummary' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Principal, IDL.Float64))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'listExpenses' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Vec(Expense)],
      ['query'],
    ),
  'listGroups' : IDL.Func([], [IDL.Vec(SharedExpenseGroup)], ['query']),
  'listSharedExpenses' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(SharedExpense)],
      ['query'],
    ),
  'markSplitPaid' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'removeGroupMember' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setMonthlyBudget' : IDL.Func([IDL.Text, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LivingSituation = IDL.Variant({
    'withParents' : IDL.Null,
    'onCampus' : IDL.Null,
    'offCampus' : IDL.Null,
  });
  const ConflictFrequency = IDL.Variant({
    'often' : IDL.Null,
    'never' : IDL.Null,
    'sometimes' : IDL.Null,
    'rarely' : IDL.Null,
  });
  const IncomeSource = IDL.Variant({
    'scholarship' : IDL.Null,
    'other' : IDL.Null,
    'partTimeJob' : IDL.Null,
    'allowance' : IDL.Null,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const BudgetDisciplineLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'findsAppsUseful' : IDL.Bool,
    'previousAppName' : IDL.Opt(IDL.Text),
    'tracksDailyExpenses' : IDL.Bool,
    'livingSituation' : LivingSituation,
    'biggestFinancialProblem' : IDL.Text,
    'name' : IDL.Text,
    'featurePreferences' : IDL.Vec(IDL.Text),
    'conflictFrequency' : ConflictFrequency,
    'incomeSource' : IncomeSource,
    'borrowsDueToBudget' : IDL.Bool,
    'majorSpendingCategory' : IDL.Text,
    'gender' : Gender,
    'financialStressLevel' : IDL.Nat,
    'hasSharedExpenses' : IDL.Bool,
    'course' : IDL.Text,
    'prefersAutoSplit' : IDL.Bool,
    'hasEmergencySavings' : IDL.Bool,
    'setsMonthlyBudget' : IDL.Bool,
    'monthEndShortage' : IDL.Bool,
    'monthlyIncome' : IDL.Float64,
    'budgetDisciplineLevel' : BudgetDisciplineLevel,
  });
  const Expense = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const SharedExpenseGroup = IDL.Record({
    'id' : IDL.Nat,
    'creator' : IDL.Principal,
    'members' : IDL.Vec(IDL.Principal),
    'name' : IDL.Text,
  });
  const SharedExpense = IDL.Record({
    'id' : IDL.Nat,
    'settlements' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Bool)),
    'splitType' : IDL.Variant({ 'custom' : IDL.Null, 'equal' : IDL.Null }),
    'description' : IDL.Text,
    'groupId' : IDL.Nat,
    'totalAmount' : IDL.Float64,
    'customSplits' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Float64)),
    'paidBy' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCustomCategory' : IDL.Func([IDL.Text], [], []),
    'addExpense' : IDL.Func(
        [IDL.Float64, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'addGroupMember' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'addSharedExpense' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Float64,
          IDL.Principal,
          IDL.Variant({ 'custom' : IDL.Null, 'equal' : IDL.Null }),
          IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Float64)),
        ],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGroup' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'deleteCustomCategory' : IDL.Func([IDL.Text], [], []),
    'deleteExpense' : IDL.Func([IDL.Nat], [], []),
    'deleteGroup' : IDL.Func([IDL.Nat], [], []),
    'editExpense' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'getAlerts' : IDL.Func(
        [IDL.Text],
        [
          IDL.Vec(
            IDL.Record({
              'alertType' : IDL.Variant({
                'warning' : IDL.Null,
                'exceeded' : IDL.Null,
                'critical' : IDL.Null,
              }),
              'message' : IDL.Text,
              'category' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getBudgetSummary' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'categories' : IDL.Vec(
              IDL.Record({
                'limit' : IDL.Float64,
                'totalSpent' : IDL.Float64,
                'percentageUsed' : IDL.Float64,
                'category' : IDL.Text,
                'remaining' : IDL.Float64,
              })
            ),
            'totalIncome' : IDL.Float64,
            'incomeToExpenseRatio' : IDL.Float64,
            'totalExpenses' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFinancialScore' : IDL.Func(
        [],
        [
          IDL.Record({
            'savingTips' : IDL.Vec(IDL.Text),
            'highestSpendingCategory' : IDL.Text,
            'emergencyFundRecommendation' : IDL.Float64,
            'disciplineLevel' : IDL.Text,
            'weeklySpendingCap' : IDL.Float64,
            'borrowingRisk' : IDL.Text,
            'monthlyTrend' : IDL.Vec(
              IDL.Record({ 'month' : IDL.Text, 'total' : IDL.Float64 })
            ),
            'financialScore' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getSettlementSummary' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Principal, IDL.Float64))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'listExpenses' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Vec(Expense)],
        ['query'],
      ),
    'listGroups' : IDL.Func([], [IDL.Vec(SharedExpenseGroup)], ['query']),
    'listSharedExpenses' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(SharedExpense)],
        ['query'],
      ),
    'markSplitPaid' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'removeGroupMember' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setMonthlyBudget' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };